name: TpCmdPlugin
version: 1.0
main: dev.tpcmd.TpCmdPlugin
api-version: 1.21
commands:
  tpcreate:
    description: Create a teleport command
    usage: /tpcreate <name>
  tpdel:
    description: Delete a teleport command
    usage: /tpdel <name>
